### ISSUE TITLE
[3.x] Docs

### ISSUE THREAD

**Issue by rez1dent3** [bavix/gripmock#246]
- improve the filtering documentation
- more similar examples
- documentation on headers
- documentation on response codes
- error documentation

**Comment by kasir-barati** [comment]
Thanks for the awesome work, lemme know if I can help. Back to the topic of this issue, please add some examples where we have multiple protobuf files but (one of the is importing others). Something like this:

```proto
// common/address.proto
syntax = "proto3";

package common.address;

message Address {
  string postal_code = 4;
}

// user/user.proto
syntax = "proto3";

package user;

import "common/address.proto";

// Define User message
message User {
  string name = 1;
  common.address.Address address = 3;
}
```

This is not my real case but yeah, it is something like this and I am getting this error message in the terminal: 

```bash
docker logs 41daf268e38a
2025-02-07T14:31:50Z INF Starting GripMock release=v2.7.1
2025-02-07T14:31:50Z INF stub-manager started addr=0.0.0.0:4771
er_proto/common/feature_flag.proto: File not found.
user.proto:6:1: Import "common/address.proto" was not found or had errors.
address.proto:16:12: "common.address.Address" is not defined.
2025-02-07T14:31:50Z FTL fail on protoc error="exit status 1"
```

You can add an example for this too. Ah, and here is my docker compose file:

```yml
services:
  mocked-user:
    image: bavix/gripmock
    volumes:
      - ./src/proto:/proto:ro
      - ./mocks/user:/stubs:ro
    command: --stub=/stubs /proto/user/user.proto
```

BTW would not it be easier to use compose file in your examples instead of docker commands in terminal?
