### ISSUE TITLE
BUG: can't read yaml stub files

### ISSUE THREAD

**Issue by Muntasir2001** [bavix/gripmock#330]
Hi,

I have been trying to use Gripmock with yaml as the stub file but its showing this error.

![Screenshot 2024-07-08 at 18 39 26](https://github.com/bavix/gripmock/assets/52258261/0d4205f5-7304-4317-b5c9-083190c8e4e2)

I have tried numerous ways of creating a gripmock service in docker compose and even tried to spin up the service without using docker compose but nothing worked. I have also tried one of your older version of gripmock which didn't work either.

Here are all the files that I have used to create a Gripmock service:

```yaml
# docker-compose.yaml

services:
  gripmock:
    image: bavix/gripmock:2.6.13
    volumes:
      - ./proto:/proto
      - ./stubs:/stubs:ro
    ports:
      - '4770:4770' # GRPC server
      # - '4771:4771' # Stub server API
    command: ['--stub=/stubs' ,'/proto/hello.proto']
```

```yaml
# stubs/hello.yml

service: Gripmock
method: SayHello
input:
  equals:
    name: tokopedia-single
output:
  data:
    message: Hello Tokopedia
    return_code: 1

```

```proto

// proto/hello.proto
syntax = "proto3";
option go_package = "github.com/bavix/gripmock/protogen/example/simple";

package simple;

service Gripmock {
  rpc SayHello (Request) returns (Reply);
}

message Request {
  string name = 1;
}

message Reply {
  string message = 1;
  int32 return_code = 2;
}

```

Note: one of my colleague also tried it on his machine and it didn't work either. I have M1 pro Macbook and my colleague has intel core i5 Macbook.

**Comment by rez1dent3** [comment]
@Muntasir2001 hello. Thank you very much for the feedback.

Indeed, this leads to an unpleasant bug. I'll try to fix it soon.

For now you can replace with an array:
```yaml
-
  service: Gripmock
  method: SayHello
  input:
    equals:
      name: tokopedia-single
  output:
    data:
      message: Hello Tokopedia
      return_code: 1
```
