### ISSUE TITLE
BUG: Gripmock removes all the input fields which has 0 as the value

### ISSUE THREAD

**Issue by Muntasir2001** [bavix/gripmock#341]
Hi,

We have been testing our proto methods using Gripmock and one bug we encountered in the process is, if any input fields have the value 0, Gripmock removes those field from the JSON and then crashes.

Here is what I mean:

stub file:

```yaml
service: RTDataBase
method: WriteDataStream
input:
  equals:
    item_data:
    - item: 1
      data:
        time: 1
        time_fep: 1
        value: 1
        status: 1
      source: 1
output:
  data: {}
```

The message I am sending to this method using Postman:

```json
{
  "item_data": [
    {
      "item": 0,
      "data": {
        "time": 0,
        "time_fep": 0,
        "value": 0,
        "status": 0
      },
      "source": 0
    }
  ]
}
```

I also tried testing it using [grpcurl](https://github.com/fullstorydev/grpcurl). Here is the command which I ran to test it:
`grpcurl -plaintext  -d '{"item_data":[{"item":0,"data":{"time":0,"time_fep":0,"value":0,"status":0},"source":0}]}' \
    localhost:4770 orxa.rtdas.rtdb.api.rtdatabase.v1.RTDataBase.WriteDataStream`

Here is the log from Gripmock:
```
gripmock-1  | 2024/07/10 18:45:00 Can't find stub
gripmock-1  |
gripmock-1  | Service: RTDataBase
gripmock-1  |
gripmock-1  | Method: WriteDataStream
gripmock-1  |
gripmock-1  | Input
gripmock-1  |
gripmock-1  | {
gripmock-1  | 	"item_data": [
gripmock-1  | 		{
gripmock-1  | 			"data": {}
gripmock-1  | 		}
gripmock-1  | 	]
gripmock-1  | }
gripmock-1  | 2024-07-10T18:45:00Z INF bytes=393 code=404 elapsed=0.525125 ip=::1 method=POST ua=Go-http-client/1.1 url=/api/stubs/search
gripmock-1  |
gripmock-1  | Closest Match
gripmock-1  |
gripmock-1  | equals:{
gripmock-1  | 	"item_data": [
gripmock-1  | 		{
gripmock-1  | 			"data": {
gripmock-1  | 				"status": 1,
gripmock-1  | 				"time": 1,
gripmock-1  | 				"time_fep": 1,
gripmock-1  | 				"value": 1
gripmock-1  | 			},
gripmock-1  | 			"item": 1,
gripmock-1  | 			"source": 1
gripmock-1  | 		}
gripmock-1  | 	]
gripmock-1  | }
```

**Comment by rez1dent3** [comment]
Hello. I couldn't reproduce your problem.
```proto
// proto/simple.proto
syntax = "proto3";

package orxa.rtdas.rtdb.api.rtdatabase.v1;

service RTDataBase {
  rpc WriteDataStream (WriteDataStreamRequest) returns (WriteDataStreamResponse) {}
}

message WriteDataStreamRequest {
  message Data {
    uint32 time = 1;
    uint32 time_fep = 2;
    uint32 value = 3;
    uint32 status = 4;
  }

  message ItemData {
    uint32 item = 1;
    Data data = 2;
    uint32 source = 3;
  }

  repeated ItemData item_data = 1;
}

message WriteDataStreamResponse {
  string message = 1;
}
```

```yaml
# stubs/first.yaml
service: RTDataBase
method: WriteDataStream
input:
  equals:
    item_data:
      - item: 1
        data:
          time: 1
          time_fep: 1
          value: 1
          status: 1
        source: 1
output:
  data:
    message: ok
```

```yaml
# docker-compose.yaml
services:
  gripmock:
    image: bavix/gripmock:2
    ports:
      - 4770:4770
      - 4771:4771
    healthcheck:
      test: "curl --connect-timeout 1 --silent --show-error --fail http://gripmock:4771/api/health/readiness"
      timeout: 1s
      interval: 1s
      start_period: 1s
      retries: 10
    command:
      - -stub=/stubs
      - /proto/simple.proto
    volumes:
      - ./stubs:/stubs:ro
      - ./proto:/proto:ro

```

<img width="1123" alt="Screenshot 2024-07-10 at 23 10 48" src="https://github.com/bavix/gripmock/assets/5111255/398d3078-fbc5-4caa-a07c-0ee71414ae7b">
