### ISSUE TITLE
Can not mock value for google.protobuf.Timestamp field type

### ISSUE THREAD

**Issue by NikolayMoshkin** [bavix/gripmock#550]
I have run into a problem with setting mocks for structures that include a protobuf.Timestamp type.

For example for a counters structure:
```
message Counters {
  protobuf.Timestamp LastActive = 17;
}
```

I can't figure out how I can set a value for such a field over http.

```
I tried:
curl -X POST -d '{"service":"CLABCountersLimits","method":"GetCounters","input":{"equals":{"ID":1}},"output":{"data":{ "LastActive":1743749152}}' localhost:4771/api/stubs

Try to get the mock:
grpcurl -plaintext -d '{"ID":1}' localhost:4770 clabcl.CLABCountersLimits/GetCounters

Got an error: ‘proto: syntax error (line 1:231): unexpected token 1743749152’
```

I also tried to set LastActive as string ‘2024-06-21T16:38:39.607823Z’, as unit timestamp as string ‘1743749152’, but facing with the same issue

How can I set mock value for that type?

**Comment by rez1dent3** [comment]
Hello. Write the gripmock version, please

**Comment by NikolayMoshkin** [comment]
```
docker image list|grep bavix/gripmock
bavix/gripmock      latest
```

**Comment by rez1dent3** [comment]
GripMock writes what version it launched when it starts. Can you send the log? The thing is that latest is the last tag that was built and you switch between v2 and v3 versions.

**Comment by NikolayMoshkin** [comment]
Starting GripMock release=v3.0.0

**Comment by rez1dent3** [comment]
Got here a little earlier)

`docker-compose.yaml`
```yaml
services:
  mockserver:
    image: bavix/gripmock:3
    ports:
      - 4770:4770
      - 4771:4771
    command:
      - --stub=/stubs
      - /proto/helloworld.proto
    volumes:
      - ./helloworld.yaml:/stubs/helloworld.yaml:ro
      - ./helloworld.proto:/proto/helloworld.proto:ro
```

`helloworld.proto`
```proto
syntax = "proto3";

import "google/protobuf/timestamp.proto";

package helloworld;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
  google.protobuf.Timestamp last_updated = 2;
}
```

`helloworld.yaml`
```yaml
- service: Greeter
  method: SayHello
  input:
    equals:
      name: gripmock
  output:
    data:
      message: Hello, GripMock
      last_updated: "2025-04-04T16:22:39.607823+03:00"

```

Test:
```sh
➜  ~ grpcurl -plaintext -d '{"name": "gripmock"}' localhost:4770 helloworld.Greeter/SayHello
{
  "message": "Hello, GripMock",
  "lastUpdated": "2025-04-04T13:22:39.607823Z"
}
```

GripMock UI: 

![Image](https://github.com/user-attachments/assets/fa79d2f7-eac9-487c-8fc6-5786f42189a2)
